---
title: "hw_1"
author: "Sonish Lamsal, Emmie Jenkins"
date: "1/27/2021"
output: pdf_document
---
## Question 1(a)
```{r error=TRUE}
divide <- function(d,a) {
  if (a==0) stop("division by zero is undefined.")
  if (d<0 || a<0) stop("divide() only works for positive ‘a‘ and ‘d‘.")
  quotient <- 0
    while (a<=d){
      d = d - a
      quotient = quotient + 1
    }
  c(q = quotient, r = d)
}  
divide(22, 7)
22 %/% 7
22 %% 7
divide(22, 0)
divide(-22,7)
divide(21,7)
```

## Question 1(b)
```{r}
mod <- function(d,a) {
  a<- divide(d,a)
  unname(a[2])
}
mod(23, 7)
mod(21,7)
```

## Question 1(c)

### The remainer is positive when d and a have the same sign 
### The remainder is neagtive when d and a have different signs
```{r}
-22 %%  7
-22 %% -7
 22 %%  7
 22 %% -7
```

## Question 1(d)
```{r}
is.divisor <- function(d,a) {
  if (a==0){
    rem <- 1
  }
  else rem <- mod(abs(d),abs(a))
  rem == 0
}
is.divisor(6, 3)
is.divisor(6, 4)
is.divisor(-6, 3)
is.divisor(6, 0)
```

## Question 1(e)
```{r error=TRUE}
divisors <- function(d) {
  if (d==0) stop("Input cannot be zero")
  num <- c(-abs(d):abs(d))
  check <- lapply(num, is.divisor, d=d)
  num[unlist(check)]
}
divisors(7)
divisors(18)
```

## Question 1(f)
```{r}
gcd_naive <- function(a,b) {
  if ( a!=0 && b!=0){
    div_a <- divisors(a)
    div_b <- divisors(b)
    common <- intersect(div_a, div_b)
    gcd <- max(common)
  }
  else{
    gcd <-  max(abs(a),abs(b))
  }
  gcd
}
gcd_naive(64, 28)
gcd_naive(64, -28)
gcd_naive(64,0)
gcd_naive(-64,0)
gcd_naive(0,0)
```

## Question 1(g)
```{r}
is.prime_naive <- function(p) {
  div <- divisors(p)
  length(div) == 4
}
is.prime_naive(5)
is.prime_naive(20)
is.prime_naive(1)
is.prime_naive(-3)
```

## Question 1(h)
```{r}
naive_seive <- function(n) {
  num <- c(1:n)
  check <- lapply(num, is.prime_naive)
  num[unlist(check)]
}
naive_seive(100)
```

## Question 1(i)
```{r}
eratosthenes_sieve <- function(n) {
  numbers <- c(2:n)
  check <- rep(TRUE, n-1)
  value <- floor(sqrt(n))
  for (i in 2:value) {
    mul <- n %/% i
    for (j in 2:mul) {
      check[match(i*j,numbers)] <- FALSE
    }
  }
  numbers[check]
}
eratosthenes_sieve(100)

```

## Question 1(j)
```{r}
is.relprime <- function(a, b) {
  gcd_naive(a, b) == 1
}
is.relprime(9, 16)
is.relprime(6, 21)
```

## Question 1(k)
```{r}
gcd_recursive <- function(a, b, quiet=TRUE) {
  if (quiet == FALSE) {
    cat("(",a,",",b,")\n")
  }
  if (a==0 && b==0) 0
  if (a==0 || b==0){
    max(abs(a),abs(b))
  }
  else{
    c <- abs(min(a,b))
    d <- abs(max(a,b))
    d <- mod(d,c)
    gcd_recursive(c,d, quiet)
  }
}
gcd_recursive( 64,  28, quiet = FALSE)
gcd_recursive( 64, -28)
gcd_recursive( 64,   0)
gcd_recursive(-64,   0)
gcd_recursive(  0,   0)
```

## Question 1(l)
```{r}
gcd <- function(a,b, quiet = TRUE) {
  if (quiet == FALSE) {
    cat("(",a,",",b,")\n")
  }
  if (a==0 && b==0) 0
  else if (a==0 || b==0) max(abs(a),abs(b))
  else {
    while (a!=0 && b!=0) {
      c <- abs(min(a,b))
      d <- abs(max(a,b))
      a <- c
      b <- mod(d,c)
      if (quiet == FALSE) {
        cat("(",a,",",b,")\n")
      }
    }
    max(abs(a),abs(b))
  }
  
}
gcd( 64,  28, quiet = FALSE)
gcd( 64, -28)
gcd( 64,   0)
gcd(-64,   0)
gcd(  0,   0)
```

## Question 1(m)
```{r}
library(bench)
(result <- mark(
  gcd(64,28),
  gcd_recursive(64,28),
  relative = TRUE
))
```


## Question 2(a)

```{r error=TRUE}

inv <- function(b, x0 = 10^-((ceiling(log10(abs(b))))), tol = sqrt(.Machine$double.eps), 
                message = FALSE) {
  if (b==0) stop("zero has no multiplicative inverse")
  dif <- 1 #initilaizing a difference > tol
  if (b > 0){ #for positive input b
    while (dif > tol){
    y <- x0 #setting the intial x iteration to y
    x0 <- x0 * (2 - b * x0) 
    dif <- x0 - y #subtracting the newly iteration from the previous iteration
      if (message) cat(x0, sep = "\n") #for message=TRUE
    }
    if (message) cat(x0, sep = "\n")
    x0
  }
  else { #for negative input b
    -inv(-b)
  }
}
  

inv(1000, message = TRUE)
inv(-1000)

```

## Queation 2(b)
```{r error=TRUE}
divide_real_fast <- function(a, b) {
  if (b==0) stop("division by zero is undefined.")
  a * inv(b)
}

divide_real_fast(22, 7)

divide_real_fast(2, -4)

divide_real_fast(2, 0)
```

## Question 2(c)
```{r}
divide_fast <- function(a, d){
  divide(a,d)
  c <- zapsmall(divide_real_fast(a,d))
  floor_c <- floor(c)
  t <- c - floor_c
  q <- floor_c 
  r <- round(d * t) #computing remainder and rounding
  c(q = q, r = r)
}

a <- 1e8; d <- 2
divide(a, d)
divide_fast(a, d)
a %/% d
a %% d

```